Enhance the rebase functionality to be more resumable (#357)
This handles the case where `upgrade-provider` fails due to patch
conflicts. In that case the user has to fix them and run `git rebase
--continue` themselves. They also have to remember to run
`./scripts/upstream.sh check_in` before re-running the tool. This PR
updates the rebase logic to only require the user to run `git rebase
--continue` once they fix the rebase conflicts, the tool can continue
from there.

This `upgrade-provider` tool is meant to abstract the process of
upgrading the provider. When the rebase fails it dumps you out and tells
you to fix the rebase before continuing. Currently we also expect the
user to know the implementation detail of _also_ needing to run
`check_in`. This PR attempts to remove that requirement.

**Example rebase error message for reference**

```console
  - update patched provider
    - ✓ /opt/homebrew/bin/git submodule update --force --init: done
    - ✓ /opt/homebrew/bin/git fetch --tags: done
    - ✓ /opt/homebrew/bin/git reset HEAD --hard: done
    - ✓ ./scripts/upstream.sh checkout: done
    - X ./scripts/upstream.sh rebase -o refs/tags/v6.47.0: exit status 1:
error: could not apply 83b04967e... docs patching
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config advice.mergeConflict false"
```