Exit non-zero on error (#131)
Fixes #130

We change how errors are displayed on invalid config files. The error message for an
invalid config file now looks like this:

```sh
𝛌 upgrade-provider pulumi/pulumi-aiven
error: While parsing config: yaml: line 4: did not find expected ',' or '}'
```

It used to look like this:

```sh
𝛌 upgrade-provider pulumi/pulumi-aiven
Error: While parsing config: yaml: line 4: did not find expected ',' or '}'
Usage:
  upgrade-provider <provider> [flags]

Flags:
      --allow-missing-docs              If true, don't error on missing docs during tfgen.
                                        This is equivalent to setting PULUMI_MISSING_DOCS_ERROR=${! VALUE}.
      --create-failure-issue            Create an issue in the target repository if the upgrade attempt fails in CI.
      --experimental                    Enable experimental features, such as auto token mapping and auto aliasing
  -h, --help                            help for upgrade-provider

...
```